== About the Original Author

I like to know how things work. At an early age this would consist of asking “Why?” followed but countless further “Why?”. Without realising it, like many other children, I had stumbled upon the “5 Whys” to root cause analysis, or, if you’d ask Grandma she’d probably say my approach was the “50 Whys”!

This questioning of how the Universe worked resulted in attending the University of Nottingham to attain a degree in Physics. I was fortunate enough to get a grant in addition to a government loan to get me through. I suspect in today’s climate of the cost of University I would have either chosen something more vocational or chosen another path. But  I wanted to know how things worked. The course was challenging and I was glad to complete it and enter the world of business. I had two options at the time, either to join IBM and probably go to Edinburgh or join Hyperknowledge, a small tech company in Cambridge. The latter offered share options and pre dotcom bubble the world was our oyster. We had a fantastic team and great fun. However, the dotcom bubble passed by, the company had missed it’s opportunity. I was also getting fidgety after 3 years at the same place and made a rather rash decision to leave and go contracting. After those 3 years of being employed, I went contracting for the foreseeable.

I setup a company to provide IT consultancy and support services to local companies. I went through the Yahoo! Directory for local companies, opened their website, and sent them a sales e-mail. I continued for a while manually doing this, then realised there must be a way I could programmatically do this, and started thinking about how to write software to do this. However, like most things, somebody had already done this, and I found Atomic e-mail hunter to get these e-mail addresses. I recall my small dining room table filled with all the old desktops and laptops that I had at my disposal running the software to collect e-mail addresses. I then had another machine that sent the e-mails out in bulk. I collected around 10,000 e-mails. This was enough to get a couple of sales leads and a couple of projects and provide support for local companies and get me by. I wouldn’t recommend this strategy in today’s more stringent climate though – but needs must!

Then one day whilst driving back from London, I had a call from a recruitment company for Suffolk Constabulary who were looking for a developer with Microsoft experience. I offered to drive there straight away and indeed redirected up the A12 and got the contract.

Since then I have done a large number of contracts involving Microsoft technologies and in particular involving Microsoft SharePoint.

One such contract was with Publicis Modem who had won a contract with the Army Recruiting Group to build services such as their website relating to recruiting soldiers. Publicis Modem didn’t have Microsoft resources, they were more open source orientated. Initially, we subcontracted the work to a Microsoft Gold Partner, but I also started to build up our own internal team. If I say so myself, we built a fantastic team and had a lot of fun in the process.

At Cielo Costa, I helped recruit another fantastic team that provided IT consultancy and support services around Microsoft technologies. We had developers in the Philippines, India, Poland and the UK. I also helped put together the project process of how to deliver IT projects consistently. A large part of the thought process behind this methodology was forged whilst at Cielo Costa.

I am now the CEO of KnowAll Ltd, a boutique consultancy specializing in artificial intelligence solutions. At KnowAll AI, we assist businesses in leveraging AI to drive growth and profitability. Our mission is to facilitate the positive growth of artificial intelligence by providing enterprises with leading-edge AI solutions that offer tangible benefits to their operations and customers. We focus on helping organizations understand the potential of AI and implement solutions that deliver measurable results.
