name: Simple Book Build

on:
  workflow_dispatch:  # Only manual triggering for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Debug - List repository files
        run: ls -la
      
      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor ruby
          sudo gem install asciidoctor-pdf
          asciidoctor --version
      
      - name: Build HTML version first for testing
        run: |
          asciidoctor -a toc Book.asciidoc -o book.html
          echo "HTML build result:"
          ls -la book.html || echo "HTML build failed"
      
      - name: Build PDF
        run: |
          echo "Starting PDF build..."
          asciidoctor-pdf Book.asciidoc -o book.pdf || echo "PDF build failed but continuing"
          echo "PDF build result:"
          ls -la book.pdf || echo "PDF file not found"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: book-files
          path: |
            book.html
            book.pdf
          if-no-files-found: warn
      
      - name: Manual release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          files: |
            book.html
            book.pdf
          tag_name: manual-build-${{ github.run_number }}
          name: Manual Book Build ${{ github.run_number }}
          body: |
            This is a manually triggered build of the T-Minus-15 book.
            
            Files included:
            - HTML (for web viewing)
            - PDF (for printing and Amazon KDP)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
