name: Book Build for Amazon KDP

on:
  workflow_dispatch:  # Manual triggering for testing
  push:
    tags:        # Run automatically on tags
      - 'v*'     # Run on version tags like v0.1.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed for release creation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Asciidoctor and extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor ruby calibre
          sudo gem install asciidoctor-pdf
          sudo gem install --pre asciidoctor-epub3
          asciidoctor --version
      
      - name: Build PDF
        run: |
          echo "Starting PDF build..."
          asciidoctor-pdf Book.asciidoc -o t-minus-15.pdf
          echo "PDF build complete, checking file:"
          ls -la t-minus-15.pdf
      
      - name: Build EPUB
        run: |
          echo "Starting EPUB build..."
          asciidoctor-epub3 Book.asciidoc -o t-minus-15.epub || echo "EPUB build failed, but continuing"
          echo "EPUB result:"
          ls -la t-minus-15.epub || echo "EPUB file not found"
      
      - name: Build MOBI (for older Kindle devices)
        run: |
          echo "Converting EPUB to MOBI..."
          [ -f t-minus-15.epub ] && ebook-convert t-minus-15.epub t-minus-15.mobi || echo "MOBI conversion skipped"
          ls -la t-minus-15.mobi || echo "MOBI file not found"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: book-files
          path: |
            t-minus-15.pdf
            t-minus-15.epub
            t-minus-15.mobi
          if-no-files-found: warn
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            t-minus-15.pdf
            t-minus-15.epub
            t-minus-15.mobi
          tag_name: ${{ github.ref_name || format('build-{0}', github.run_number) }}
          name: T-Minus-15 Book ${{ github.ref_name || format('Build {0}', github.run_number) }}
          prerelease: ${{ startsWith(github.ref_name, 'v0.') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          body: |
            T-Minus-15: Secrets of an Elite DevOps Team
            
            Files included:
            - PDF (for printing and Amazon KDP)
            - EPUB (for e-readers and Kindle)
            - MOBI (for older Kindle devices)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
