name: Build Book for Amazon KDP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install Asciidoctor and extensions
        run: |
          gem install asciidoctor
          gem install asciidoctor-pdf
          gem install asciidoctor-epub3 || true
          
      - name: Install additional fonts
        run: |
          mkdir -p ~/.fonts
          cp -r Fonts/* ~/.fonts/ || true
          fc-cache -f -v
          
      - name: Create main book file
        run: |
          cat > Book.asciidoc << 'EOF'
          = T-Minus-15: Secrets of an Elite DevOps Team
          Ben G. Weeks
          :doctype: book
          :toc:
          :toclevels: 3
          :sectnums:
          :sectnumlevels: 3
          :imagesdir: Images
          :front-cover-image: 01-3.png
          :stylesheet: CSS/tminus15-styles.css
          
          include::AboutTheAuthor.asciidoc[]
          
          include::Foreword.asciidoc[]
          
          include::Sponsors.asciidoc[]
          
          include::WhatsThisAllAbout.asciidoc[]
          
          == Decoding the client's wants and needs
          include::DecodingTheClientsWantsAndNeeds.asciidoc[]
          
          == Crafting great user experiences
          include::CraftingGreatUserExperiences.asciidoc[]
          
          == Let's get Agile!
          include::LetsGetAgile.asciidoc[]
          
          == So what about DevOps?
          include::SoWhatAboutDevOps.asciidoc[]
          
          == The Avengers of Agile: Assembling a Cross-Functional Squad That Delivers Results
          include::TheAvengersOfAgile.asciidoc[]
          
          == Raising the Bar: The Pursuit of Quality in Agile Projects
          include::RaisingTheBar.asciidoc[]
          
          == Delivering value
          include::DeliveringValue.asciidoc[]
          
          == Happy customers
          include::HappyCustomers.asciidoc[]
          
          == 15-steps to success
          include::15StepsToSuccess.asciidoc[]
          
          [appendix]
          == Epic metadata
          include::EpicMetadata.asciidoc[]
          
          [appendix]
          == Feature metadata
          include::FeatureMetadata.asciidoc[]
          
          [appendix]
          == User Story metadata
          include::UserStoryMetadata.asciidoc[]
          
          [appendix]
          == Task metadata
          include::TaskMetadata.asciidoc[]
          
          [appendix]
          == Bugs and Enhancements metadata
          include::BugsAndEnhancementsMetadata.asciidoc[]
          
          [appendix]
          == WIP limits
          include::WIPLimits.asciidoc[]
          
          [appendix]
          == Meetings
          include::Meetings.asciidoc[]
          
          [appendix]
          == Azure DevOps Process Template Setup
          include::AzureDevOpsProcessTemplateSetup.asciidoc[]
          
          include::Thanks.asciidoc[]
          EOF
          
      - name: Create PDF theme
        run: |
          cat > tminus15-theme.yml << 'EOF'
          extends: default
          page:
            layout: portrait
            margin: [0.75in, 1in, 0.75in, 1in]
            size: Letter
          base:
            font-family: Times-Roman
            font-size: 12
          heading:
            font-family: Helvetica
          title-page:
            align: center
          EOF
          
      - name: Build PDF
        run: |
          asciidoctor-pdf -a pdf-theme=tminus15-theme.yml Book.asciidoc -o T-Minus-15.pdf
          echo "PDF build complete, check results"
          ls -la T-Minus-15.pdf
          
      - name: Build EPUB (optional)
        run: |
          asciidoctor-epub3 Book.asciidoc -o T-Minus-15.epub || echo "EPUB build failed, continuing anyway"
          
      - name: Save artifacts in workspace
        run: |
          mkdir -p book-output
          cp T-Minus-15.pdf book-output/ || echo "No PDF found"
          cp T-Minus-15.epub book-output/ || echo "No EPUB found"
          echo "Saved artifacts to book-output directory"
          ls -la book-output/
          
      # Create tag-based release only if this is a tag push
      - name: Create release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            T-Minus-15.pdf
            T-Minus-15.epub
          draft: false
          prerelease: ${{ startsWith(github.ref_name, 'v0.') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          name: T-Minus-15 Book Release ${{ github.ref_name }}
          body: |
            ${{ startsWith(github.ref_name, 'v0.') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') && 'Pre-release build of T-Minus-15 book for testing/review. Not production-ready.' || 'Book compiled for Amazon KDP' }}

            Files included:
            - PDF (for printing and Amazon KDP)
            - EPUB (for e-readers)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
