name: Basic Book Build

on:
  workflow_dispatch:  # Manual triggering only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Asciidoctor and PDF extension
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor
          sudo gem install asciidoctor-pdf
          asciidoctor --version
          echo "Current directory contents:"
          ls -la
          echo "Book.asciidoc exists?"
          ls -la Book.asciidoc || echo "Book.asciidoc not found"
      
      - name: Build PDF
        run: |
          echo "Starting PDF build..."
          asciidoctor-pdf Book.asciidoc -o book.pdf || echo "PDF build failed"
          echo "PDF build result:"
          ls -la book.pdf || echo "PDF file not found"
          echo "Build directory contents:"
          ls -la
      
      - name: Debug build results
        run: |
          echo "Current directory: $(pwd)"
          echo "All files in current directory:"
          find . -type f -name "*.pdf" -o -name "*.epub"
          echo "Build complete"
          
      # Just create a release on the current commit
      - name: Create GitHub Release directly
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a tag for this manual build
          TAG_NAME="manual-build-$(date +%Y%m%d-%H%M%S)"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          
          # Use the GitHub CLI to create a release
          if [ -f "book.pdf" ]; then
            gh release create $TAG_NAME \
              --title "T-Minus-15 Manual Build $(date +%Y-%m-%d)" \
              --notes "Manual build of T-Minus-15 book" \
              book.pdf
            echo "Created release with PDF attached"
          else
            gh release create $TAG_NAME \
              --title "T-Minus-15 Build (No PDF)" \
              --notes "Build failed to generate PDF"
            echo "Created release but PDF was not found"
          fi
